# --- Configuration ==================================================================
# Used only to SCORE a candidate MVTec root during discovery. The categories actually
# processed are whatever Local Output contains -- see CATS_SEEN in section 2.
CATS  = ["can", "fabric", "fruit_jelly", "rice",
         "sheet_metal", "vial", "wallplugs", "walnuts"]
SEEDS = [0, 1, 2]

# HOW MANY IMAGES. This is the knob you actually turn.
# Corpus size = len(LIVE_CATS) x len(SEEDS) x N_SYNTH.
#   proof of concept   1  ->  8 x 3 x 1 =  24 images     <- current
#   small run          4  ->  8 x 3 x 4 =  96
#   full run          24  ->  8 x 3 x 24 = 576
# All three seeds are kept even at PoC size: the seed is what varies the blob, the bank entry
# and the rotation, so dropping seeds would hide exactly the variation this is meant to show.
N_SYNTH = 1
N_HOSTS = 32        # ceiling on the host pool per category

WORK_SIZE = 1024    # synthesis resolution (paper Table 3)

# --- MRSP + OBS (paper 3.4) ---------------------------------------------------------
AD2_NOISE_SCALE = 14
OCTAVES_FBM     = 6
PERSISTENCE     = 0.8
MRSP_ALPHA      = 1.5     # 1/f^alpha spectral decay -- NOT in the paper's Table 3; it should be
SINGLE_BLOB     = True
MIN_BLOB_PX     = 25
AD2_COVERAGE    = 0.018

# Empty-frame gate. Relative, not absolute: across eight categories normal OBS coverage runs
# from a few scattered wallplugs to a fabric sheet filling the frame, so one fixed fraction
# would either pass every empty walnuts tray or reject every good vial.
MIN_OBJ_COV_REL = 0.40
MIN_OBJ_COV_ABS = 0.02

# --- Placement (paper 3.5, Algorithm 4) ---------------------------------------------
PLACE_MODE    = "real_scale"   # the defect replays at its TRUE relative size
ROTATE        = True
PLACEMENT_MIX = 0.5            # fraction of samples generated by mode B
GAMMA_RANGE   = (0.20, 0.60)   # defect's share of the blob, drawn per sample
GAMMA_S_RANGE = (0.15, 2.50)
CONTAIN_T     = 0.90
R_EQ_POISSON  = 16.0           # below this, route to alpha

# --- Compositing --------------------------------------------------------------------
BETA          = 1.0
FEATHER_PX    = 1.5
COLLAR_FRAC   = 0.25
COLLAR_MIN_PX = 6
COLLAR_KEEP_R = 0.5
DEFECT_T      = 6.0

# A composite whose GT region differs from the host by less than this (mean |out-host| over the
# GT, 0-255) carries no findable defect. 8/255 is ~3% mean channel change: below that the edit
# sits at sensor-noise level. It is a REPORTING threshold -- nothing is dropped. Poisson erasing
# a small defect is a property of the operator, not a bug, and removing those samples would
# quietly flatter it.
DISSOLVED_T   = 8.0

# --- Bank ---------------------------------------------------------------------------
# LOADED, not built. Stages 2-3 extracted and validated these crops; this notebook spends them.
# That split is the "generate once, synthesise many" architecture -- re-extracting here would
# bypass the VLM gate and silently put rejected crops back into the corpus.
MIN_ENTRY_CFRAC = 0.10   # re-applied on load as a guard; the bank already passed it

# Only used when the bank ships WITHOUT a manifest. defect_frac = defect_long_px / this, and it
# is the one field that cannot be recovered from a crop PNG: a 322px defect from a 2448px frame
# and the same 322px from a 1024px frame are different sizes relative to the object. Wrong here
# means every defect is placed at the wrong scale, so the notebook says loudly when it is used.
SOURCE_LONG_PX = 2448    # MVTec AD 2 native long side

DEFECT_KIND = {"rice": "foreign_object",   "walnuts": "surface",
               "wallplugs": "foreign_object", "fruit_jelly": "foreign_object",
               "can": "surface",           "fabric": "surface",
               "sheet_metal": "surface",   "vial": "foreign_object"}

# --- Output -------------------------------------------------------------------------
OUT_ROOT  = "/kaggle/working" if os.path.isdir("/kaggle/working") else "out_stage45"
FINAL_DIR = os.path.join(OUT_ROOT, "Final Synthetic Images")
os.makedirs(OUT_ROOT, exist_ok=True)

# Dataset ref OR literal path. A kaggle URL and an "owner/slug" both work: mount_candidates()
# in section 2 expands them, because Kaggle mounts the same dataset at different paths on
# different kernels (/kaggle/input/<slug> vs /kaggle/input/datasets/<owner>/<slug>).
BANK_ID = "/kaggle/input/datasets/abhaykdas/defect-bank"        # Stage 2-3 output
AD2_ID  = "/kaggle/input/datasets/abhaykdas/mvtec-ad2-reducded"  # normals for hosts

print(f"target: {len(SEEDS)} seeds x {N_SYNTH} per category "
      f"(x however many categories the bank has)")
print(f"output -> {FINAL_DIR}")
